# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pybert/view/pybert_gui.ui',
# licensing of 'pybert/view/pybert_gui.ui' applies.
#
# Created: Fri Oct 11 22:41:31 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from pybert.view.widgets import QuadGraphicsLayout
from pyqtgraph import GraphicsLayoutWidget, PlotWidget
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 895)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.config_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tx_equalization = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tx_equalization.sizePolicy().hasHeightForWidth())
        self.tx_equalization.setSizePolicy(sizePolicy)
        self.tx_equalization.setObjectName("tx_equalization")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tx_equalization)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tx_equalization)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setChecked(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.tx_ami_filename = QtWidgets.QLineEdit(self.groupBox_7)
        self.tx_ami_filename.setObjectName("tx_ami_filename")
        self.horizontalLayout_2.addWidget(self.tx_ami_filename)
        self.load_tx_ami_file = QtWidgets.QPushButton(self.groupBox_7)
        self.load_tx_ami_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_tx_ami_file.setText("")
        self.load_tx_ami_file.setObjectName("load_tx_ami_file")
        self.horizontalLayout_2.addWidget(self.load_tx_ami_file)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.tx_dll_filename = QtWidgets.QLineEdit(self.groupBox_7)
        self.tx_dll_filename.setObjectName("tx_dll_filename")
        self.horizontalLayout_2.addWidget(self.tx_dll_filename)
        self.load_tx_dll_file = QtWidgets.QPushButton(self.groupBox_7)
        self.load_tx_dll_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_tx_dll_file.setText("")
        self.load_tx_dll_file.setObjectName("load_tx_dll_file")
        self.horizontalLayout_2.addWidget(self.load_tx_dll_file)
        self.configure_tx = QtWidgets.QPushButton(self.groupBox_7)
        self.configure_tx.setObjectName("configure_tx")
        self.horizontalLayout_2.addWidget(self.configure_tx)
        self.tx_use_getwave = QtWidgets.QCheckBox(self.groupBox_7)
        self.tx_use_getwave.setObjectName("tx_use_getwave")
        self.horizontalLayout_2.addWidget(self.tx_use_getwave)
        self.verticalLayout_17.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tx_equalization)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_24.addWidget(self.tableWidget)
        self.verticalLayout_17.addWidget(self.groupBox_8)
        self.gridLayout.addWidget(self.tx_equalization, 1, 0, 1, 1)
        self.simulation_control = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.simulation_control.sizePolicy().hasHeightForWidth())
        self.simulation_control.setSizePolicy(sizePolicy)
        self.simulation_control.setObjectName("simulation_control")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.simulation_control)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setObjectName("formLayout_17")
        self.bitRateGbpsLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.bitRateGbpsLabel_3.setObjectName("bitRateGbpsLabel_3")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bitRateGbpsLabel_3)
        self.bit_rate = QtWidgets.QLineEdit(self.simulation_control)
        self.bit_rate.setObjectName("bit_rate")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bit_rate)
        self.nbitsLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.nbitsLabel_3.setObjectName("nbitsLabel_3")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nbitsLabel_3)
        self.nbits = QtWidgets.QLineEdit(self.simulation_control)
        self.nbits.setObjectName("nbits")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nbits)
        self.nspbLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.nspbLabel_3.setObjectName("nspbLabel_3")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nspbLabel_3)
        self.nspb = QtWidgets.QLineEdit(self.simulation_control)
        self.nspb.setObjectName("nspb")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nspb)
        self.modulationLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.modulationLabel_3.setObjectName("modulationLabel_3")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.modulationLabel_3)
        self.mod_type = QtWidgets.QComboBox(self.simulation_control)
        self.mod_type.setObjectName("mod_type")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mod_type)
        self.gridLayout_5.addLayout(self.formLayout_17, 0, 0, 1, 1)
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setObjectName("formLayout_18")
        self.sweepSimulationLabel = QtWidgets.QLabel(self.simulation_control)
        self.sweepSimulationLabel.setObjectName("sweepSimulationLabel")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sweepSimulationLabel)
        self.sweepSimulationCheckBox = QtWidgets.QCheckBox(self.simulation_control)
        self.sweepSimulationCheckBox.setObjectName("sweepSimulationCheckBox")
        self.formLayout_18.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.sweepSimulationCheckBox
        )
        self.sweepAvesLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.sweepAvesLabel_3.setObjectName("sweepAvesLabel_3")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sweepAvesLabel_3)
        self.sweep_aves = QtWidgets.QLineEdit(self.simulation_control)
        self.sweep_aves.setObjectName("sweep_aves")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sweep_aves)
        self.patternLengthLabel = QtWidgets.QLabel(self.simulation_control)
        self.patternLengthLabel.setObjectName("patternLengthLabel")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.patternLengthLabel)
        self.pattern_len = QtWidgets.QLineEdit(self.simulation_control)
        self.pattern_len.setObjectName("pattern_len")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pattern_len)
        self.eyeBitsLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.eyeBitsLabel_3.setObjectName("eyeBitsLabel_3")
        self.formLayout_18.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.eyeBitsLabel_3)
        self.eye_bits = QtWidgets.QLineEdit(self.simulation_control)
        self.eye_bits.setObjectName("eye_bits")
        self.formLayout_18.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eye_bits)
        self.gridLayout_5.addLayout(self.formLayout_18, 0, 1, 1, 1)
        self.formLayout_24 = QtWidgets.QFormLayout()
        self.formLayout_24.setObjectName("formLayout_24")
        self.vodVLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.vodVLabel_3.setObjectName("vodVLabel_3")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.vodVLabel_3)
        self.vod = QtWidgets.QLineEdit(self.simulation_control)
        self.vod.setObjectName("vod")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vod)
        self.rnVLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.rnVLabel_3.setObjectName("rnVLabel_3")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rnVLabel_3)
        self.random_noise = QtWidgets.QLineEdit(self.simulation_control)
        self.random_noise.setObjectName("random_noise")
        self.formLayout_24.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.random_noise)
        self.pnVLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.pnVLabel_3.setObjectName("pnVLabel_3")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pnVLabel_3)
        self.periodic_noise = QtWidgets.QLineEdit(self.simulation_control)
        self.periodic_noise.setObjectName("periodic_noise")
        self.formLayout_24.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.periodic_noise)
        self.fPnMHzLabel_3 = QtWidgets.QLabel(self.simulation_control)
        self.fPnMHzLabel_3.setObjectName("fPnMHzLabel_3")
        self.formLayout_24.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fPnMHzLabel_3)
        self.f_pn = QtWidgets.QLineEdit(self.simulation_control)
        self.f_pn.setObjectName("f_pn")
        self.formLayout_24.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.f_pn)
        self.gridLayout_5.addLayout(self.formLayout_24, 0, 2, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.simulation_control)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_20.sizePolicy().hasHeightForWidth())
        self.groupBox_20.setSizePolicy(sizePolicy)
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_35 = QtWidgets.QLabel(self.groupBox_20)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_23.addWidget(self.label_35)
        self.thresh = QtWidgets.QLineEdit(self.groupBox_20)
        self.thresh.setObjectName("thresh")
        self.horizontalLayout_23.addWidget(self.thresh)
        self.label_36 = QtWidgets.QLabel(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_23.addWidget(self.label_36)
        self.impulse_response_length = QtWidgets.QLineEdit(self.groupBox_20)
        self.impulse_response_length.setObjectName("impulse_response_length")
        self.horizontalLayout_23.addWidget(self.impulse_response_length)
        self.gridLayout_5.addWidget(self.groupBox_20, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.simulation_control, 0, 0, 1, 1)
        self.cdr_parameters = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cdr_parameters.sizePolicy().hasHeightForWidth())
        self.cdr_parameters.setSizePolicy(sizePolicy)
        self.cdr_parameters.setObjectName("cdr_parameters")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.cdr_parameters)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.cdr_parameters)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.delta_t = QtWidgets.QLineEdit(self.cdr_parameters)
        self.delta_t.setObjectName("delta_t")
        self.horizontalLayout_7.addWidget(self.delta_t)
        self.label_7 = QtWidgets.QLabel(self.cdr_parameters)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.alpha = QtWidgets.QLineEdit(self.cdr_parameters)
        self.alpha.setObjectName("alpha")
        self.horizontalLayout_7.addWidget(self.alpha)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.cdr_parameters)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.lock_num_averages = QtWidgets.QLineEdit(self.cdr_parameters)
        self.lock_num_averages.setObjectName("lock_num_averages")
        self.horizontalLayout_6.addWidget(self.lock_num_averages)
        self.label_9 = QtWidgets.QLabel(self.cdr_parameters)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lock_tolerance = QtWidgets.QLineEdit(self.cdr_parameters)
        self.lock_tolerance.setObjectName("lock_tolerance")
        self.horizontalLayout_6.addWidget(self.lock_tolerance)
        self.label_10 = QtWidgets.QLabel(self.cdr_parameters)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lock_sustain = QtWidgets.QLineEdit(self.cdr_parameters)
        self.lock_sustain.setObjectName("lock_sustain")
        self.horizontalLayout_6.addWidget(self.lock_sustain)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.cdr_parameters, 2, 0, 1, 1)
        self.dfe_parameters = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dfe_parameters.sizePolicy().hasHeightForWidth())
        self.dfe_parameters.setSizePolicy(sizePolicy)
        self.dfe_parameters.setCheckable(True)
        self.dfe_parameters.setObjectName("dfe_parameters")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.dfe_parameters)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.checkBox = QtWidgets.QCheckBox(self.dfe_parameters)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_15.addWidget(self.checkBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.dfe_parameters)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.dfe_num_taps = QtWidgets.QLineEdit(self.dfe_parameters)
        self.dfe_num_taps.setObjectName("dfe_num_taps")
        self.horizontalLayout_5.addWidget(self.dfe_num_taps)
        self.label_2 = QtWidgets.QLabel(self.dfe_parameters)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dfe_gain = QtWidgets.QLineEdit(self.dfe_parameters)
        self.dfe_gain.setObjectName("dfe_gain")
        self.horizontalLayout_5.addWidget(self.dfe_gain)
        self.label_3 = QtWidgets.QLabel(self.dfe_parameters)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.dfe_level = QtWidgets.QLineEdit(self.dfe_parameters)
        self.dfe_level.setObjectName("dfe_level")
        self.horizontalLayout_5.addWidget(self.dfe_level)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.dfe_parameters)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dfe_num_averages = QtWidgets.QLineEdit(self.dfe_parameters)
        self.dfe_num_averages.setObjectName("dfe_num_averages")
        self.horizontalLayout_4.addWidget(self.dfe_num_averages)
        self.label_5 = QtWidgets.QLabel(self.dfe_parameters)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.dfe_bw = QtWidgets.QLineEdit(self.dfe_parameters)
        self.dfe_bw.setObjectName("dfe_bw")
        self.horizontalLayout_4.addWidget(self.dfe_bw)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.dfe_parameters, 2, 1, 1, 1)
        self.channel_parameters = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.channel_parameters.sizePolicy().hasHeightForWidth())
        self.channel_parameters.setSizePolicy(sizePolicy)
        self.channel_parameters.setObjectName("channel_parameters")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.channel_parameters)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox_11 = QtWidgets.QGroupBox(self.channel_parameters)
        self.groupBox_11.setCheckable(True)
        self.groupBox_11.setChecked(False)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_32 = QtWidgets.QLabel(self.groupBox_11)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_21.addWidget(self.label_32)
        self.channel_filename = QtWidgets.QLineEdit(self.groupBox_11)
        self.channel_filename.setObjectName("channel_filename")
        self.horizontalLayout_21.addWidget(self.channel_filename)
        self.load_channel_file = QtWidgets.QPushButton(self.groupBox_11)
        self.load_channel_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_channel_file.setText("")
        self.load_channel_file.setObjectName("load_channel_file")
        self.horizontalLayout_21.addWidget(self.load_channel_file)
        self.zero_padded = QtWidgets.QCheckBox(self.groupBox_11)
        self.zero_padded.setObjectName("zero_padded")
        self.horizontalLayout_21.addWidget(self.zero_padded)
        self.windowed = QtWidgets.QCheckBox(self.groupBox_11)
        self.windowed.setObjectName("windowed")
        self.horizontalLayout_21.addWidget(self.windowed)
        self.label_33 = QtWidgets.QLabel(self.groupBox_11)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_21.addWidget(self.label_33)
        self.channel_f_step = QtWidgets.QLineEdit(self.groupBox_11)
        self.channel_f_step.setObjectName("channel_f_step")
        self.horizontalLayout_21.addWidget(self.channel_f_step)
        self.label_34 = QtWidgets.QLabel(self.groupBox_11)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_21.addWidget(self.label_34)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_19.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.channel_parameters)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.tx_RsOhmsLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.tx_RsOhmsLabel_3.setObjectName("tx_RsOhmsLabel_3")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tx_RsOhmsLabel_3)
        self.tx_rs = QtWidgets.QLineEdit(self.groupBox_12)
        self.tx_rs.setObjectName("tx_rs")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tx_rs)
        self.tx_CoutPFLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.tx_CoutPFLabel_3.setObjectName("tx_CoutPFLabel_3")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tx_CoutPFLabel_3)
        self.tx_cout = QtWidgets.QLineEdit(self.groupBox_12)
        self.tx_cout.setObjectName("tx_cout")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tx_cout)
        self.lengthMLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.lengthMLabel_3.setObjectName("lengthMLabel_3")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lengthMLabel_3)
        self.channel_length = QtWidgets.QLineEdit(self.groupBox_12)
        self.channel_length.setObjectName("channel_length")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.channel_length)
        self.materialLabel = QtWidgets.QLabel(self.groupBox_12)
        self.materialLabel.setObjectName("materialLabel")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.materialLabel)
        self.material = QtWidgets.QComboBox(self.groupBox_12)
        self.material.setObjectName("material")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.material)
        self.gridLayout_7.addLayout(self.formLayout_14, 0, 0, 1, 1)
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.formLayout_15.setObjectName("formLayout_15")
        self.lossTangentLabel = QtWidgets.QLabel(self.groupBox_12)
        self.lossTangentLabel.setObjectName("lossTangentLabel")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lossTangentLabel)
        self.loss_tangent = QtWidgets.QLineEdit(self.groupBox_12)
        self.loss_tangent.setObjectName("loss_tangent")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loss_tangent)
        self.z0OhmsLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.z0OhmsLabel_3.setObjectName("z0OhmsLabel_3")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.z0OhmsLabel_3)
        self.z0 = QtWidgets.QLineEdit(self.groupBox_12)
        self.z0.setObjectName("z0")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.z0)
        self.v_relCLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.v_relCLabel_3.setObjectName("v_relCLabel_3")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.v_relCLabel_3)
        self.v_rel = QtWidgets.QLineEdit(self.groupBox_12)
        self.v_rel.setObjectName("v_rel")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.v_rel)
        self.gridLayout_7.addLayout(self.formLayout_15, 0, 1, 1, 1)
        self.formLayout_16 = QtWidgets.QFormLayout()
        self.formLayout_16.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.formLayout_16.setObjectName("formLayout_16")
        self.rx_RinOhmsLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.rx_RinOhmsLabel_3.setObjectName("rx_RinOhmsLabel_3")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rx_RinOhmsLabel_3)
        self.rx_rin = QtWidgets.QLineEdit(self.groupBox_12)
        self.rx_rin.setObjectName("rx_rin")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rx_rin)
        self.rx_CinPFLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.rx_CinPFLabel_3.setObjectName("rx_CinPFLabel_3")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rx_CinPFLabel_3)
        self.rx_cin = QtWidgets.QLineEdit(self.groupBox_12)
        self.rx_cin.setObjectName("rx_cin")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rx_cin)
        self.rx_CacUFLabel_3 = QtWidgets.QLabel(self.groupBox_12)
        self.rx_CacUFLabel_3.setObjectName("rx_CacUFLabel_3")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rx_CacUFLabel_3)
        self.rx_cac = QtWidgets.QLineEdit(self.groupBox_12)
        self.rx_cac.setObjectName("rx_cac")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rx_cac)
        self.gridLayout_7.addLayout(self.formLayout_16, 0, 2, 1, 1)
        self.verticalLayout_19.addWidget(self.groupBox_12)
        self.gridLayout.addWidget(self.channel_parameters, 0, 1, 1, 1)
        self.rx_equalization = QtWidgets.QGroupBox(self.config_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.rx_equalization.sizePolicy().hasHeightForWidth())
        self.rx_equalization.setSizePolicy(sizePolicy)
        self.rx_equalization.setObjectName("rx_equalization")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.rx_equalization)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.rx_equalization)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setCheckable(True)
        self.groupBox_9.setChecked(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_3.addWidget(self.label_24)
        self.rx_ami_filename = QtWidgets.QLineEdit(self.groupBox_9)
        self.rx_ami_filename.setObjectName("rx_ami_filename")
        self.horizontalLayout_3.addWidget(self.rx_ami_filename)
        self.load_rx_ami_file = QtWidgets.QPushButton(self.groupBox_9)
        self.load_rx_ami_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_rx_ami_file.setText("")
        self.load_rx_ami_file.setObjectName("load_rx_ami_file")
        self.horizontalLayout_3.addWidget(self.load_rx_ami_file)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.rx_dll_filename = QtWidgets.QLineEdit(self.groupBox_9)
        self.rx_dll_filename.setObjectName("rx_dll_filename")
        self.horizontalLayout_3.addWidget(self.rx_dll_filename)
        self.load_rx_dll_file = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_rx_dll_file.sizePolicy().hasHeightForWidth())
        self.load_rx_dll_file.setSizePolicy(sizePolicy)
        self.load_rx_dll_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_rx_dll_file.setText("")
        self.load_rx_dll_file.setObjectName("load_rx_dll_file")
        self.horizontalLayout_3.addWidget(self.load_rx_dll_file)
        self.configure_rx = QtWidgets.QPushButton(self.groupBox_9)
        self.configure_rx.setObjectName("configure_rx")
        self.horizontalLayout_3.addWidget(self.configure_rx)
        self.rx_use_getwave = QtWidgets.QCheckBox(self.groupBox_9)
        self.rx_use_getwave.setObjectName("rx_use_getwave")
        self.horizontalLayout_3.addWidget(self.rx_use_getwave)
        self.verticalLayout_18.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.rx_equalization)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.ctle_from_file = QtWidgets.QGroupBox(self.groupBox_10)
        self.ctle_from_file.setCheckable(True)
        self.ctle_from_file.setChecked(False)
        self.ctle_from_file.setObjectName("ctle_from_file")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ctle_from_file)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_37 = QtWidgets.QLabel(self.ctle_from_file)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.label_37)
        self.ctle_filename = QtWidgets.QLineEdit(self.ctle_from_file)
        self.ctle_filename.setObjectName("ctle_filename")
        self.horizontalLayout_8.addWidget(self.ctle_filename)
        self.load_ctle_from_file = QtWidgets.QPushButton(self.ctle_from_file)
        self.load_ctle_from_file.setMaximumSize(QtCore.QSize(40, 16777215))
        self.load_ctle_from_file.setText("")
        self.load_ctle_from_file.setObjectName("load_ctle_from_file")
        self.horizontalLayout_8.addWidget(self.load_ctle_from_file)
        self.verticalLayout_20.addWidget(self.ctle_from_file)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_38 = QtWidgets.QLabel(self.groupBox_10)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_25.addWidget(self.label_38)
        self.ctle_fp = QtWidgets.QLineEdit(self.groupBox_10)
        self.ctle_fp.setObjectName("ctle_fp")
        self.horizontalLayout_25.addWidget(self.ctle_fp)
        self.label_39 = QtWidgets.QLabel(self.groupBox_10)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_25.addWidget(self.label_39)
        self.ctle_bandwidth = QtWidgets.QLineEdit(self.groupBox_10)
        self.ctle_bandwidth.setObjectName("ctle_bandwidth")
        self.horizontalLayout_25.addWidget(self.ctle_bandwidth)
        self.verticalLayout_20.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_40 = QtWidgets.QLabel(self.groupBox_10)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_26.addWidget(self.label_40)
        self.ctle_boost = QtWidgets.QLineEdit(self.groupBox_10)
        self.ctle_boost.setObjectName("ctle_boost")
        self.horizontalLayout_26.addWidget(self.ctle_boost)
        self.label_41 = QtWidgets.QLabel(self.groupBox_10)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_26.addWidget(self.label_41)
        self.ctle_mode = QtWidgets.QComboBox(self.groupBox_10)
        self.ctle_mode.setObjectName("ctle_mode")
        self.horizontalLayout_26.addWidget(self.ctle_mode)
        self.ctle_dc_offset_2 = QtWidgets.QLineEdit(self.groupBox_10)
        self.ctle_dc_offset_2.setObjectName("ctle_dc_offset_2")
        self.horizontalLayout_26.addWidget(self.ctle_dc_offset_2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_26)
        self.verticalLayout_18.addWidget(self.groupBox_10)
        self.gridLayout.addWidget(self.rx_equalization, 1, 1, 1, 1)
        self.tabWidget.addTab(self.config_tab, "")
        self.dfe_tab = QtWidgets.QWidget()
        self.dfe_tab.setObjectName("dfe_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dfe_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plot_dfe = GraphicsLayoutWidget(self.dfe_tab)
        self.plot_dfe.setObjectName("plot_dfe")
        self.verticalLayout_3.addWidget(self.plot_dfe)
        self.tabWidget.addTab(self.dfe_tab, "")
        self.eq_tab = QtWidgets.QWidget()
        self.eq_tab.setObjectName("eq_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.eq_tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.eq_tx_equalization = QtWidgets.QGroupBox(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.eq_tx_equalization.sizePolicy().hasHeightForWidth())
        self.eq_tx_equalization.setSizePolicy(sizePolicy)
        self.eq_tx_equalization.setObjectName("eq_tx_equalization")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.eq_tx_equalization)
        self.verticalLayout_21.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.eq_tx_equalization)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setAlternatingRowColors(True)
        self.tableWidget_6.setRowCount(4)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget_6.verticalHeader().setVisible(False)
        self.verticalLayout_21.addWidget(self.tableWidget_6)
        self.gridLayout_4.addWidget(self.eq_tx_equalization, 0, 0, 1, 1)
        self.eq_tuning_options = QtWidgets.QGroupBox(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.eq_tuning_options.sizePolicy().hasHeightForWidth())
        self.eq_tuning_options.setSizePolicy(sizePolicy)
        self.eq_tuning_options.setObjectName("eq_tuning_options")
        self.formLayout_10 = QtWidgets.QFormLayout(self.eq_tuning_options)
        self.formLayout_10.setObjectName("formLayout_10")
        self.maxIterationsLabel = QtWidgets.QLabel(self.eq_tuning_options)
        self.maxIterationsLabel.setObjectName("maxIterationsLabel")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.maxIterationsLabel)
        self.maxIterations = QtWidgets.QLineEdit(self.eq_tuning_options)
        self.maxIterations.setObjectName("maxIterations")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxIterations)
        self.relativeOptLabel = QtWidgets.QLabel(self.eq_tuning_options)
        self.relativeOptLabel.setObjectName("relativeOptLabel")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.relativeOptLabel)
        self.relativeOpt = QtWidgets.QLineEdit(self.eq_tuning_options)
        self.relativeOpt.setReadOnly(True)
        self.relativeOpt.setObjectName("relativeOpt")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.relativeOpt)
        self.pRZFErrorLabel = QtWidgets.QLabel(self.eq_tuning_options)
        self.pRZFErrorLabel.setObjectName("pRZFErrorLabel")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pRZFErrorLabel)
        self.pRZFError = QtWidgets.QLineEdit(self.eq_tuning_options)
        self.pRZFError.setReadOnly(True)
        self.pRZFError.setObjectName("pRZFError")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pRZFError)
        self.gridLayout_4.addWidget(self.eq_tuning_options, 0, 3, 1, 1)
        self.eq_rx_equalization = QtWidgets.QGroupBox(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.eq_rx_equalization.sizePolicy().hasHeightForWidth())
        self.eq_rx_equalization.setSizePolicy(sizePolicy)
        self.eq_rx_equalization.setObjectName("eq_rx_equalization")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.eq_rx_equalization)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.cTLEFpGHzLabel = QtWidgets.QLabel(self.eq_rx_equalization)
        self.cTLEFpGHzLabel.setObjectName("cTLEFpGHzLabel")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cTLEFpGHzLabel)
        self.cTLEFpGHz = QtWidgets.QLineEdit(self.eq_rx_equalization)
        self.cTLEFpGHz.setObjectName("cTLEFpGHz")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cTLEFpGHz)
        self.bandwidthGHzLabel = QtWidgets.QLabel(self.eq_rx_equalization)
        self.bandwidthGHzLabel.setObjectName("bandwidthGHzLabel")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bandwidthGHzLabel)
        self.bandwidth = QtWidgets.QLineEdit(self.eq_rx_equalization)
        self.bandwidth.setObjectName("bandwidth")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bandwidth)
        self.cTLEBoostDBLabel = QtWidgets.QLabel(self.eq_rx_equalization)
        self.cTLEBoostDBLabel.setObjectName("cTLEBoostDBLabel")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cTLEBoostDBLabel)
        self.cTLEBoost = QtWidgets.QLineEdit(self.eq_rx_equalization)
        self.cTLEBoost.setObjectName("cTLEBoost")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cTLEBoost)
        self.verticalLayout_22.addLayout(self.formLayout_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_29 = QtWidgets.QLabel(self.eq_rx_equalization)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.ctle_modes = QtWidgets.QComboBox(self.eq_rx_equalization)
        self.ctle_modes.setObjectName("ctle_modes")
        self.horizontalLayout.addWidget(self.ctle_modes)
        self.ctle_dc_offset = QtWidgets.QLineEdit(self.eq_rx_equalization)
        self.ctle_dc_offset.setObjectName("ctle_dc_offset")
        self.horizontalLayout.addWidget(self.ctle_dc_offset)
        self.verticalLayout_22.addLayout(self.horizontalLayout)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.eq_use_dfe = QtWidgets.QCheckBox(self.eq_rx_equalization)
        self.eq_use_dfe.setObjectName("eq_use_dfe")
        self.horizontalLayout_15.addWidget(self.eq_use_dfe)
        self.label_30 = QtWidgets.QLabel(self.eq_rx_equalization)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.eq_num_of_dfe_taps = QtWidgets.QLineEdit(self.eq_rx_equalization)
        self.eq_num_of_dfe_taps.setObjectName("eq_num_of_dfe_taps")
        self.horizontalLayout_15.addWidget(self.eq_num_of_dfe_taps)
        self.verticalLayout_22.addLayout(self.horizontalLayout_15)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.label_31 = QtWidgets.QLabel(self.eq_rx_equalization)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_23.addWidget(self.label_31)
        self.gridLayout_4.addWidget(self.eq_rx_equalization, 0, 2, 1, 1)
        self.plot_eq = PlotWidget(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plot_eq.sizePolicy().hasHeightForWidth())
        self.plot_eq.setSizePolicy(sizePolicy)
        self.plot_eq.setObjectName("plot_eq")
        self.gridLayout_4.addWidget(self.plot_eq, 1, 0, 1, 4)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.reset_eq = QtWidgets.QPushButton(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_eq.sizePolicy().hasHeightForWidth())
        self.reset_eq.setSizePolicy(sizePolicy)
        self.reset_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.reset_eq.setDefault(False)
        self.reset_eq.setFlat(False)
        self.reset_eq.setObjectName("reset_eq")
        self.eq_buttons = QtWidgets.QButtonGroup(MainWindow)
        self.eq_buttons.setObjectName("eq_buttons")
        self.eq_buttons.addButton(self.reset_eq)
        self.horizontalLayout_16.addWidget(self.reset_eq)
        self.save_eq = QtWidgets.QPushButton(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_eq.sizePolicy().hasHeightForWidth())
        self.save_eq.setSizePolicy(sizePolicy)
        self.save_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.save_eq.setDefault(False)
        self.save_eq.setFlat(False)
        self.save_eq.setObjectName("save_eq")
        self.eq_buttons.addButton(self.save_eq)
        self.horizontalLayout_16.addWidget(self.save_eq)
        self.opt_tx_eq = QtWidgets.QPushButton(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_tx_eq.sizePolicy().hasHeightForWidth())
        self.opt_tx_eq.setSizePolicy(sizePolicy)
        self.opt_tx_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.opt_tx_eq.setDefault(False)
        self.opt_tx_eq.setFlat(False)
        self.opt_tx_eq.setObjectName("opt_tx_eq")
        self.eq_buttons.addButton(self.opt_tx_eq)
        self.horizontalLayout_16.addWidget(self.opt_tx_eq)
        self.opt_rx_eq = QtWidgets.QPushButton(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opt_rx_eq.sizePolicy().hasHeightForWidth())
        self.opt_rx_eq.setSizePolicy(sizePolicy)
        self.opt_rx_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.opt_rx_eq.setDefault(False)
        self.opt_rx_eq.setFlat(False)
        self.opt_rx_eq.setObjectName("opt_rx_eq")
        self.eq_buttons.addButton(self.opt_rx_eq)
        self.horizontalLayout_16.addWidget(self.opt_rx_eq)
        self.coopt_eq = QtWidgets.QPushButton(self.eq_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coopt_eq.sizePolicy().hasHeightForWidth())
        self.coopt_eq.setSizePolicy(sizePolicy)
        self.coopt_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.coopt_eq.setDefault(False)
        self.coopt_eq.setFlat(False)
        self.coopt_eq.setObjectName("coopt_eq")
        self.eq_buttons.addButton(self.coopt_eq)
        self.horizontalLayout_16.addWidget(self.coopt_eq)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 2, 0, 1, 1)
        self.tabWidget.addTab(self.eq_tab, "")
        self.impulse_tab = QtWidgets.QWidget()
        self.impulse_tab.setObjectName("impulse_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.impulse_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_impulse = QuadGraphicsLayout(self.impulse_tab)
        self.plot_impulse.setObjectName("plot_impulse")
        self.verticalLayout_4.addWidget(self.plot_impulse)
        self.tabWidget.addTab(self.impulse_tab, "")
        self.step_tab = QtWidgets.QWidget()
        self.step_tab.setObjectName("step_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.step_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plot_step = QuadGraphicsLayout(self.step_tab)
        self.plot_step.setObjectName("plot_step")
        self.verticalLayout_5.addWidget(self.plot_step)
        self.tabWidget.addTab(self.step_tab, "")
        self.pulse_tab = QtWidgets.QWidget()
        self.pulse_tab.setObjectName("pulse_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pulse_tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plot_pulse = QuadGraphicsLayout(self.pulse_tab)
        self.plot_pulse.setObjectName("plot_pulse")
        self.verticalLayout_6.addWidget(self.plot_pulse)
        self.tabWidget.addTab(self.pulse_tab, "")
        self.freq_tab = QtWidgets.QWidget()
        self.freq_tab.setObjectName("freq_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.freq_tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plot_freq = QuadGraphicsLayout(self.freq_tab)
        self.plot_freq.setObjectName("plot_freq")
        self.verticalLayout_7.addWidget(self.plot_freq)
        self.tabWidget.addTab(self.freq_tab, "")
        self.output_tab = QtWidgets.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.output_tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plot_output = QuadGraphicsLayout(self.output_tab)
        self.plot_output.setObjectName("plot_output")
        self.verticalLayout_8.addWidget(self.plot_output)
        self.tabWidget.addTab(self.output_tab, "")
        self.eye_tab = QtWidgets.QWidget()
        self.eye_tab.setObjectName("eye_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.eye_tab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.plot_eye = QuadGraphicsLayout(self.eye_tab)
        self.plot_eye.setObjectName("plot_eye")
        self.verticalLayout_9.addWidget(self.plot_eye)
        self.tabWidget.addTab(self.eye_tab, "")
        self.jitter_dist_tab = QtWidgets.QWidget()
        self.jitter_dist_tab.setObjectName("jitter_dist_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.jitter_dist_tab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.plot_jitter_dist = QuadGraphicsLayout(self.jitter_dist_tab)
        self.plot_jitter_dist.setObjectName("plot_jitter_dist")
        self.verticalLayout_10.addWidget(self.plot_jitter_dist)
        self.tabWidget.addTab(self.jitter_dist_tab, "")
        self.jitter_spect_tab = QtWidgets.QWidget()
        self.jitter_spect_tab.setObjectName("jitter_spect_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.jitter_spect_tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.plot_jitter_spect = QuadGraphicsLayout(self.jitter_spect_tab)
        self.plot_jitter_spect.setObjectName("plot_jitter_spect")
        self.verticalLayout_11.addWidget(self.plot_jitter_spect)
        self.tabWidget.addTab(self.jitter_spect_tab, "")
        self.bathtub_tab = QtWidgets.QWidget()
        self.bathtub_tab.setObjectName("bathtub_tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.bathtub_tab)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.plot_bathtub = QuadGraphicsLayout(self.bathtub_tab)
        self.plot_bathtub.setObjectName("plot_bathtub")
        self.verticalLayout_12.addWidget(self.plot_bathtub)
        self.tabWidget.addTab(self.bathtub_tab, "")
        self.jitter_info_tab = QtWidgets.QWidget()
        self.jitter_info_tab.setObjectName("jitter_info_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.jitter_info_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QtWidgets.QLabel(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        self.jitter_info_dfe = QtWidgets.QTableWidget(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jitter_info_dfe.sizePolicy().hasHeightForWidth())
        self.jitter_info_dfe.setSizePolicy(sizePolicy)
        self.jitter_info_dfe.setMaximumSize(QtCore.QSize(16777215, 283))
        self.jitter_info_dfe.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jitter_info_dfe.setAlternatingRowColors(True)
        self.jitter_info_dfe.setShowGrid(True)
        self.jitter_info_dfe.setRowCount(4)
        self.jitter_info_dfe.setColumnCount(3)
        self.jitter_info_dfe.setObjectName("jitter_info_dfe")
        self.jitter_info_dfe.setColumnCount(3)
        self.jitter_info_dfe.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_dfe.setHorizontalHeaderItem(2, item)
        self.jitter_info_dfe.horizontalHeader().setStretchLastSection(False)
        self.jitter_info_dfe.verticalHeader().setVisible(False)
        self.jitter_info_dfe.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.jitter_info_dfe, 5, 0, 1, 1)
        self.jitter_info_tx = QtWidgets.QTableWidget(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jitter_info_tx.sizePolicy().hasHeightForWidth())
        self.jitter_info_tx.setSizePolicy(sizePolicy)
        self.jitter_info_tx.setMaximumSize(QtCore.QSize(16777215, 283))
        self.jitter_info_tx.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jitter_info_tx.setAlternatingRowColors(True)
        self.jitter_info_tx.setShowGrid(True)
        self.jitter_info_tx.setRowCount(4)
        self.jitter_info_tx.setColumnCount(3)
        self.jitter_info_tx.setObjectName("jitter_info_tx")
        self.jitter_info_tx.setColumnCount(3)
        self.jitter_info_tx.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_tx.setHorizontalHeaderItem(2, item)
        self.jitter_info_tx.horizontalHeader().setStretchLastSection(False)
        self.jitter_info_tx.verticalHeader().setVisible(False)
        self.jitter_info_tx.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.jitter_info_tx, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.jitter_info_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 4, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.jitter_info_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 4, 0, 1, 1)
        self.jitter_info_ctle = QtWidgets.QTableWidget(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jitter_info_ctle.sizePolicy().hasHeightForWidth())
        self.jitter_info_ctle.setSizePolicy(sizePolicy)
        self.jitter_info_ctle.setMaximumSize(QtCore.QSize(16777215, 283))
        self.jitter_info_ctle.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.jitter_info_ctle.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jitter_info_ctle.setAlternatingRowColors(True)
        self.jitter_info_ctle.setShowGrid(True)
        self.jitter_info_ctle.setRowCount(4)
        self.jitter_info_ctle.setColumnCount(3)
        self.jitter_info_ctle.setObjectName("jitter_info_ctle")
        self.jitter_info_ctle.setColumnCount(3)
        self.jitter_info_ctle.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_ctle.setHorizontalHeaderItem(2, item)
        self.jitter_info_ctle.horizontalHeader().setStretchLastSection(False)
        self.jitter_info_ctle.verticalHeader().setVisible(False)
        self.jitter_info_ctle.verticalHeader().setCascadingSectionResizes(False)
        self.jitter_info_ctle.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.jitter_info_ctle, 3, 1, 1, 1)
        self.jitter_info_total = QtWidgets.QTableWidget(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jitter_info_total.sizePolicy().hasHeightForWidth())
        self.jitter_info_total.setSizePolicy(sizePolicy)
        self.jitter_info_total.setMaximumSize(QtCore.QSize(16777215, 283))
        self.jitter_info_total.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.jitter_info_total.setAlternatingRowColors(True)
        self.jitter_info_total.setShowGrid(True)
        self.jitter_info_total.setRowCount(4)
        self.jitter_info_total.setColumnCount(3)
        self.jitter_info_total.setObjectName("jitter_info_total")
        self.jitter_info_total.setColumnCount(3)
        self.jitter_info_total.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jitter_info_total.setHorizontalHeaderItem(2, item)
        self.jitter_info_total.horizontalHeader().setStretchLastSection(False)
        self.jitter_info_total.verticalHeader().setVisible(False)
        self.jitter_info_total.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.jitter_info_total, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.jitter_info_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 2)
        self.tabWidget.addTab(self.jitter_info_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.sweep_table = QtWidgets.QTableWidget(self.tab)
        self.sweep_table.setAlternatingRowColors(True)
        self.sweep_table.setRowCount(1)
        self.sweep_table.setObjectName("sweep_table")
        self.sweep_table.setColumnCount(4)
        self.sweep_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sweep_table.setHorizontalHeaderItem(3, item)
        self.sweep_table.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.sweep_table)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Simulation = QtWidgets.QMenu(self.menubar)
        self.menu_Simulation.setObjectName("menu_Simulation")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.console = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setMinimumSize(QtCore.QSize(0, 0))
        self.console.setMaximumSize(QtCore.QSize(524287, 524287))
        self.console.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.console.setObjectName("console")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.text_edit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_edit.sizePolicy().hasHeightForWidth())
        self.text_edit.setSizePolicy(sizePolicy)
        self.text_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.text_edit.setReadOnly(True)
        self.text_edit.setMaximumBlockCount(200)
        self.text_edit.setCenterOnScroll(True)
        self.text_edit.setObjectName("text_edit")
        self.gridLayout_8.addWidget(self.text_edit, 0, 0, 1, 1)
        self.console.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.console)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionRun.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionRun.setObjectName("actionRun")
        self.actionToggleConsole = QtWidgets.QAction(MainWindow)
        self.actionToggleConsole.setCheckable(True)
        self.actionToggleConsole.setChecked(True)
        self.actionToggleConsole.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionToggleConsole.setObjectName("actionToggleConsole")
        self.actionSave_Configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.actionLoad_Configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionSave_Waveforms = QtWidgets.QAction(MainWindow)
        self.actionSave_Waveforms.setObjectName("actionSave_Waveforms")
        self.actionLoad_Waveforms = QtWidgets.QAction(MainWindow)
        self.actionLoad_Waveforms.setObjectName("actionLoad_Waveforms")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionDebug_Mode = QtWidgets.QAction(MainWindow)
        self.actionDebug_Mode.setCheckable(True)
        self.actionDebug_Mode.setChecked(True)
        self.actionDebug_Mode.setObjectName("actionDebug_Mode")
        self.action_Abort = QtWidgets.QAction(MainWindow)
        self.action_Abort.setObjectName("action_Abort")
        self.menuFile.addAction(self.actionSave_Configuration)
        self.menuFile.addAction(self.actionLoad_Configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Waveforms)
        self.menuFile.addAction(self.actionLoad_Waveforms)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionE_xit)
        self.menu_View.addAction(self.actionToggleConsole)
        self.menu_View.addAction(self.actionDebug_Mode)
        self.menu_Simulation.addAction(self.actionRun)
        self.menu_Simulation.addAction(self.action_Abort)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Help.addAction(self.actionDocumentation)
        self.menu_Help.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Simulation.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(
            self.actionToggleConsole, QtCore.SIGNAL("triggered(bool)"), self.console.setVisible
        )
        QtCore.QObject.connect(
            self.console,
            QtCore.SIGNAL("visibilityChanged(bool)"),
            self.actionToggleConsole.setChecked,
        )
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(
            QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1)
        )
        self.tx_equalization.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Tx Equalization", None, -1)
        )
        self.groupBox_7.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Use AMI Model", None, -1)
        )
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "AMI File", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "DLL File", None, -1))
        self.configure_tx.setText(
            QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1)
        )
        self.tx_use_getwave.setText(
            QtWidgets.QApplication.translate("MainWindow", "Use GetWave", None, -1)
        )
        self.groupBox_8.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Native", None, -1)
        )
        self.tableWidget.verticalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Pre-Tap", None, -1)
        )
        self.tableWidget.verticalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Post-Tap 1", None, -1)
        )
        self.tableWidget.verticalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Post-Tap 2", None, -1)
        )
        self.tableWidget.verticalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Post-Tap 3", None, -1)
        )
        self.tableWidget.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Enabled", None, -1)
        )
        self.tableWidget.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Min Val", None, -1)
        )
        self.tableWidget.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Max Val", None, -1)
        )
        self.tableWidget.horizontalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Value", None, -1)
        )
        self.tableWidget.horizontalHeaderItem(4).setText(
            QtWidgets.QApplication.translate("MainWindow", "Steps", None, -1)
        )
        self.simulation_control.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Simulation Control", None, -1)
        )
        self.bitRateGbpsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Bit Rate (Gbps)", None, -1)
        )
        self.nbitsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Nbits", None, -1)
        )
        self.nspbLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "Nspb", None, -1))
        self.modulationLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Modulation", None, -1)
        )
        self.sweepSimulationLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Sweep Simulation", None, -1)
        )
        self.sweepAvesLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Sweep Aves.", None, -1)
        )
        self.patternLengthLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Pattern Length", None, -1)
        )
        self.eyeBitsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Eye Bits", None, -1)
        )
        self.vodVLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Vod (V)", None, -1)
        )
        self.rnVLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "Rn (V)", None, -1))
        self.pnVLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "Pn (V)", None, -1))
        self.fPnMHzLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "f(Pn) (MHz)", None, -1)
        )
        self.groupBox_20.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Analysis Parameters", None, -1)
        )
        self.label_35.setText(
            QtWidgets.QApplication.translate("MainWindow", "Pj Threshold (sigma)", None, -1)
        )
        self.label_36.setText(
            QtWidgets.QApplication.translate(
                "MainWindow", "Impulse Response Length (ns)", None, -1
            )
        )
        self.cdr_parameters.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "CDR Parameters", None, -1)
        )
        self.label_6.setText(
            QtWidgets.QApplication.translate("MainWindow", "Delta-t (ps)", None, -1)
        )
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Alpha", None, -1))
        self.label_8.setText(
            QtWidgets.QApplication.translate("MainWindow", "Lock Nave.", None, -1)
        )
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Lock Tol.", None, -1))
        self.label_10.setText(
            QtWidgets.QApplication.translate("MainWindow", "Lock Sus.", None, -1)
        )
        self.dfe_parameters.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Use DFE", None, -1)
        )
        self.checkBox.setText(
            QtWidgets.QApplication.translate("MainWindow", "Ideal DFE", None, -1)
        )
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Taps", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Gain", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Level", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "N ave.", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "BW (GHz)", None, -1))
        self.channel_parameters.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Channel Parameters", None, -1)
        )
        self.groupBox_11.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "From File", None, -1)
        )
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.zero_padded.setText(
            QtWidgets.QApplication.translate("MainWindow", "Zero-Padded", None, -1)
        )
        self.windowed.setText(QtWidgets.QApplication.translate("MainWindow", "Windowed", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "f_step", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "MHz", None, -1))
        self.groupBox_12.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Native", None, -1)
        )
        self.tx_RsOhmsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Tx_Rs (Ohms)", None, -1)
        )
        self.tx_CoutPFLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Tx_Cout (pF)", None, -1)
        )
        self.lengthMLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Length (m)", None, -1)
        )
        self.materialLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Material", None, -1)
        )
        self.lossTangentLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Loss Tangent", None, -1)
        )
        self.z0OhmsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Z0 (Ohms)", None, -1)
        )
        self.v_relCLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "v_rel (c)", None, -1)
        )
        self.rx_RinOhmsLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Rx_Rin (Ohms)", None, -1)
        )
        self.rx_CinPFLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Rx_Cin (pF)", None, -1)
        )
        self.rx_CacUFLabel_3.setText(
            QtWidgets.QApplication.translate("MainWindow", "Rx_Cac (uF)", None, -1)
        )
        self.rx_equalization.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Rx Equalization", None, -1)
        )
        self.groupBox_9.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Use AMI Model", None, -1)
        )
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "AMI File", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "DLL File", None, -1))
        self.configure_rx.setText(
            QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1)
        )
        self.rx_use_getwave.setText(
            QtWidgets.QApplication.translate("MainWindow", "Use GetWave", None, -1)
        )
        self.groupBox_10.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Native", None, -1)
        )
        self.ctle_from_file.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "From File", None, -1)
        )
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.label_38.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE fp (GHz)", None, -1)
        )
        self.label_39.setText(
            QtWidgets.QApplication.translate("MainWindow", "Bandwidth (GHz)", None, -1)
        )
        self.label_40.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE Boost (dB)", None, -1)
        )
        self.label_41.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE Mode", None, -1)
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.config_tab),
            QtWidgets.QApplication.translate("MainWindow", "Configuration", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.dfe_tab),
            QtWidgets.QApplication.translate("MainWindow", "DFE", None, -1),
        )
        self.eq_tx_equalization.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Tx Equalization", None, -1)
        )
        self.tableWidget_6.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Name", None, -1)
        )
        self.tableWidget_6.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Enabled", None, -1)
        )
        self.tableWidget_6.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Min Val", None, -1)
        )
        self.tableWidget_6.horizontalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Max Val", None, -1)
        )
        self.tableWidget_6.horizontalHeaderItem(4).setText(
            QtWidgets.QApplication.translate("MainWindow", "Value", None, -1)
        )
        self.eq_tuning_options.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Tuning Options", None, -1)
        )
        self.maxIterationsLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Max Iterations", None, -1)
        )
        self.relativeOptLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Relative Opt.", None, -1)
        )
        self.pRZFErrorLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "PRZF Error", None, -1)
        )
        self.eq_rx_equalization.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Rx Equalization", None, -1)
        )
        self.cTLEFpGHzLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE fp (GHz)", None, -1)
        )
        self.bandwidthGHzLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "Bandwidth (GHz)", None, -1)
        )
        self.cTLEBoostDBLabel.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE Boost (dB)", None, -1)
        )
        self.label_29.setText(
            QtWidgets.QApplication.translate("MainWindow", "CTLE Mode", None, -1)
        )
        self.ctle_dc_offset.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "CTLE D.C. offset (dB)", None, -1)
        )
        self.eq_use_dfe.setText(
            QtWidgets.QApplication.translate("MainWindow", "Use DFE", None, -1)
        )
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Taps", None, -1))
        self.label_31.setText(
            QtWidgets.QApplication.translate(
                "MainWindow",
                "Note: Only peaking magnitude will be optimized; please set peak fequency, bandwidth and mode appropriately.",
                None,
                -1,
            )
        )
        self.reset_eq.setText(QtWidgets.QApplication.translate("MainWindow", "Reset EQ", None, -1))
        self.save_eq.setText(QtWidgets.QApplication.translate("MainWindow", "Save EQ", None, -1))
        self.opt_tx_eq.setText(QtWidgets.QApplication.translate("MainWindow", "Opt Tx", None, -1))
        self.opt_rx_eq.setText(QtWidgets.QApplication.translate("MainWindow", "Opt Rx", None, -1))
        self.coopt_eq.setText(QtWidgets.QApplication.translate("MainWindow", "Co Opt", None, -1))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.eq_tab),
            QtWidgets.QApplication.translate("MainWindow", "EQ Tune", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.impulse_tab),
            QtWidgets.QApplication.translate("MainWindow", "Impulses", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.step_tab),
            QtWidgets.QApplication.translate("MainWindow", "Steps", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.pulse_tab),
            QtWidgets.QApplication.translate("MainWindow", "Pulses", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.freq_tab),
            QtWidgets.QApplication.translate("MainWindow", "Frequency Resp.", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.output_tab),
            QtWidgets.QApplication.translate("MainWindow", "Outputs", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.eye_tab),
            QtWidgets.QApplication.translate("MainWindow", "Eyes", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.jitter_dist_tab),
            QtWidgets.QApplication.translate("MainWindow", "Jitter Dist.", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.jitter_spect_tab),
            QtWidgets.QApplication.translate("MainWindow", "Jitter Spec.", None, -1),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.bathtub_tab),
            QtWidgets.QApplication.translate("MainWindow", "Bathtubs", None, -1),
        )
        self.label_20.setText(
            QtWidgets.QApplication.translate("MainWindow", "Tx Pre-Emphasis", None, -1)
        )
        self.jitter_info_dfe.verticalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "ISI", None, -1)
        )
        self.jitter_info_dfe.verticalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "DCD", None, -1)
        )
        self.jitter_info_dfe.verticalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Pj", None, -1)
        )
        self.jitter_info_dfe.verticalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rj", None, -1)
        )
        self.jitter_info_dfe.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Input (ps)", None, -1)
        )
        self.jitter_info_dfe.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Output (ps)", None, -1)
        )
        self.jitter_info_dfe.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rejection (dB)", None, -1)
        )
        self.jitter_info_tx.verticalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "ISI", None, -1)
        )
        self.jitter_info_tx.verticalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "DCD", None, -1)
        )
        self.jitter_info_tx.verticalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Pj", None, -1)
        )
        self.jitter_info_tx.verticalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rj", None, -1)
        )
        self.jitter_info_tx.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Input (ps)", None, -1)
        )
        self.jitter_info_tx.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Output (ps)", None, -1)
        )
        self.jitter_info_tx.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rejection (dB)", None, -1)
        )
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Total", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "CTLE", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "DFE", None, -1))
        self.jitter_info_ctle.verticalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "ISI", None, -1)
        )
        self.jitter_info_ctle.verticalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "DCD", None, -1)
        )
        self.jitter_info_ctle.verticalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Pj", None, -1)
        )
        self.jitter_info_ctle.verticalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rj", None, -1)
        )
        self.jitter_info_ctle.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Input (ps)", None, -1)
        )
        self.jitter_info_ctle.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Output (ps)", None, -1)
        )
        self.jitter_info_ctle.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rejection (dB)", None, -1)
        )
        self.jitter_info_total.verticalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "ISI", None, -1)
        )
        self.jitter_info_total.verticalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "DCD", None, -1)
        )
        self.jitter_info_total.verticalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Pj", None, -1)
        )
        self.jitter_info_total.verticalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rj", None, -1)
        )
        self.jitter_info_total.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "Input (ps)", None, -1)
        )
        self.jitter_info_total.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "Output (ps)", None, -1)
        )
        self.jitter_info_total.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Rejection (dB)", None, -1)
        )
        self.label_19.setText(
            QtWidgets.QApplication.translate(
                "MainWindow", "Jitter Rejection by Equalization Component", None, -1
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.jitter_info_tab),
            QtWidgets.QApplication.translate("MainWindow", "Jitter Info", None, -1),
        )
        self.label_11.setText(
            QtWidgets.QApplication.translate("MainWindow", "Sweep Results", None, -1)
        )
        self.sweep_table.horizontalHeaderItem(0).setText(
            QtWidgets.QApplication.translate("MainWindow", "PreTap", None, -1)
        )
        self.sweep_table.horizontalHeaderItem(1).setText(
            QtWidgets.QApplication.translate("MainWindow", "PostTap", None, -1)
        )
        self.sweep_table.horizontalHeaderItem(2).setText(
            QtWidgets.QApplication.translate("MainWindow", "Mean (bit errors)", None, -1)
        )
        self.sweep_table.horizontalHeaderItem(3).setText(
            QtWidgets.QApplication.translate("MainWindow", "StdDev (bit errors)", None, -1)
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab),
            QtWidgets.QApplication.translate("MainWindow", "Sweep Info", None, -1),
        )
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_View.setTitle(QtWidgets.QApplication.translate("MainWindow", "&View", None, -1))
        self.menu_Simulation.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "&Simulation", None, -1)
        )
        self.menu_Help.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.console.setWindowTitle(
            QtWidgets.QApplication.translate("MainWindow", "Console", None, -1)
        )
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionDocumentation.setText(
            QtWidgets.QApplication.translate("MainWindow", "Documentation", None, -1)
        )
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionRun.setText(QtWidgets.QApplication.translate("MainWindow", "&Run", None, -1))
        self.actionRun.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1)
        )
        self.actionToggleConsole.setText(
            QtWidgets.QApplication.translate("MainWindow", "Console", None, -1)
        )
        self.actionToggleConsole.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+`", None, -1)
        )
        self.actionSave_Configuration.setText(
            QtWidgets.QApplication.translate("MainWindow", "Save Configuration", None, -1)
        )
        self.actionSave_Configuration.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1)
        )
        self.actionLoad_Configuration.setText(
            QtWidgets.QApplication.translate("MainWindow", "Load Configuration", None, -1)
        )
        self.actionLoad_Configuration.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1)
        )
        self.actionSave_Waveforms.setText(
            QtWidgets.QApplication.translate("MainWindow", "Save Waveforms", None, -1)
        )
        self.actionSave_Waveforms.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1)
        )
        self.actionLoad_Waveforms.setText(
            QtWidgets.QApplication.translate("MainWindow", "Load Waveforms", None, -1)
        )
        self.actionLoad_Waveforms.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+M", None, -1)
        )
        self.actionPreferences.setText(
            QtWidgets.QApplication.translate("MainWindow", "Preferences", None, -1)
        )
        self.actionPreferences.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+,", None, -1)
        )
        self.actionE_xit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, -1))
        self.actionE_xit.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1)
        )
        self.actionDebug_Mode.setText(
            QtWidgets.QApplication.translate("MainWindow", "Debug Mode", None, -1)
        )
        self.action_Abort.setText(
            QtWidgets.QApplication.translate("MainWindow", "&Abort", None, -1)
        )
        self.action_Abort.setShortcut(
            QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None, -1)
        )
