[tool.black]
line-length = 119

[tool.isort]
profile = "black"
known_first_party = ["pybert", "pyibisami"]
known_third_party = ["traits", "traitsui", "chaco", "enable"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-vv"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 119
disable="C0301,invalid-name,wrong-import-position"
