[tox]
envlist = format, py37, py38, pylint, bandit, flake8, mypy, pydocstyle, docs
skip_missing_interpreters = true

[testenv]
changedir = tests
deps =
    pytest
    pytest-cov
commands =
    py.test --basetemp={envtmpdir} -vv \
        --cov=pybert --cov-report=html --cov-report=term-missing

[testenv:bandit]
deps = bandit
commands = bandit -r {toxinidir}/pybert/

[testenv:flake8]
deps = flake8
commands = flake8 pybert

[testenv:format]
skip_install = true
deps =
    black
    isort
    autoflake
commands =
    autoflake --in-place --remove-all-unused-imports --expand-star-imports \
        --ignore-init-module-imports --recursive pybert
    isort {toxinidir}
    black {toxinidir}

[testenv:pylint]
deps = pylint
commands = pylint pybert

[testenv:mypy]
setenv =
    MYPYPATH = {toxinidir}
deps = mypy
commands = mypy -p pybert  --ignore-missing-imports

[testenv:pydocstyle]
deps = pydocstyle
commands = pydocstyle {toxinidir}/pybert --count

[testenv:docs]
deps =
    sphinx
    m2r
changedir = docs
commands =
    sphinx-apidoc -o ./ ../pybert
    sphinx-build -j auto -b html ./ {envtmpdir}/build

[flake8]
max-complexity = 10
max-line-length = 119
show-source = True
exclude = .venv, .tox, dist, docs, *.egg

[pydocstyle]
ignore = D105,D107,D203,D212,D213,D400
match = (?!gui).*\.py
