[tox]
requires = tox-conda
envlist = format, py37, pylint, bandit, flake8, docs
skip_missing_interpreters = true

[gh-actions]
python =
    3.7: py37,flake8

[testenv]
changedir = tests
deps =
    pytest
    pytest-cov
conda_deps=
    chaco
    empy
    enable
    parsec
    pyibis-ami
conda_channels=
    dbanas
    defaults
    conda-forge
commands =
    py.test --basetemp={envtmpdir} \
        --cov=pybert --cov-report=html --cov-report=term-missing

[testenv:bandit]
skip_install = true
deps = bandit
commands = bandit -r {toxinidir}/pybert/

[testenv:flake8]
skip_install = true
deps = flake8
commands = flake8 pybert

[testenv:format]
skip_install = true
deps =
    black
    isort
commands =
    isort -rc {toxinidir}/pybert {toxinidir}/tests
    black {toxinidir}/pybert {toxinidir}/tests

[testenv:pylint]
skip_install = true
deps = pylint
commands = pylint pybert

[flake8]
max-complexity = 10
max-line-length = 119
show-source = True
exclude = .venv, .tox, dist, docs, *.egg
