[tox]
envlist = py36, py37, format, pylint, flake8, docs
skip_missing_interpreters = true
skipsdist = true

[testenv]
changedir = tests
deps = 
    pytest-cov
commands = 
    py.test --basetemp={envtmpdir} -vv --cov=pybert \
            --cov-report=html --cov-report=term-missing

[testenv:format]
deps =
    isort
    black
commands =
    isort -rc {toxinidir}/pybert
    black -l 99 {toxinidir}/pybert

[testenv:pylint]
deps = 
    pylint
commands = 
    pylint --rcfile={toxinidir}/tox.ini pybert

[testenv:flake8]
deps = 
    flake8
commands = 
    flake8 pybert

[testenv:docs]
changedir = docs
deps =
    sphinx
    m2r
commands = 
    sphinx-build -j auto -b html source/ build/

[flake8]
; E501 line too long (80 > 79 characters)
; W503 line break before binary operator
ignore = W503,E501
max-line-length = 99
show-source = True
exclude = .tox, docs, venv

[MESSAGES CONTROL]

# C0301: Line too long (Handled by black)
# C0103: Doesn't conform to snake_case naming style (invalid-name) (Math)
# C0412: Imports not grouped (Handled by isort)
# C0411: third party import in wrong position (Handled by isort)
# W0703: Catching too general exception (We want the GUI to handle any error.)
disable=C0301,C0103,wrong-import-position,W0703
max-line-length = 99

[isort]
known_first_party = pybert
line_length = 99