name: PyBERT Test Suite
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Miniconda and Install PyBERT
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        environment-file: conda.recipe/pybert/meta.yaml
        python-version: ${{ matrix.python-version }}
    - name: List Conda Environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Install Dependencies
      run: |
        pip install tox tox-gh-actions
    - name: Tox
      run: |
        tox -p auto -q
