name: PyBERT Test Suite
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Miniconda and Install PyBERT
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install Conda Dependencies
      shell: bash -l {0}
      run: |
        conda install -c dbanas -c defaults -c conda-forge --only-deps pybert
        conda info
        conda list
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install tox
    - name: Tox
      shell: bash -l {0}
      run: |
        tox -p auto -e py37,flake8 -q
